In [47]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pylab as plt
import plotly.express as px

In [48]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [49]:
df = sns.load_dataset('iris')

In [50]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [51]:
df.shape

(150, 5)

In [52]:
x=df[['sepal_length','sepal_width','petal_length','petal_width']]
y = df['species']

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer,IterativeImputer
from sklearn.ensemble import VotingClassifier
from sklearn.decomposition import PCA

In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.85,shuffle=True,random_state=42)

In [55]:
x_train.shape

(127, 4)

In [56]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[127 rows x 4 columns]

In [57]:
y_train

128     virginica
131     virginica
145     virginica
108     virginica
143     virginica
          ...
71     versicolor
106     virginica
14         setosa
92     versicolor
102     virginica
Name: species, Length: 127, dtype: object

In [58]:
leble = LabelEncoder()

In [59]:
y_train_encoded = leble.fit_transform(y_train)
y_test_encoded = leble.transform(y_test)

In [60]:
scale = MinMaxScaler()

In [61]:
x_train_transformed = scale.fit_transform(x_train)

In [62]:
pca = PCA(n_components=None)

In [63]:
pca_train = pca.fit_transform(x_train_transformed)
pca_test = pca.transform(x_test)

c:\Users\91766\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning:

X has feature names, but PCA was fitted without feature names

In [64]:
col = [f"pca{i}" for i in range(1,pca_train.shape[1]+1)]

In [65]:
pcd = pd.DataFrame(pca_train,columns=col)
pcd['species'] = y_train

In [66]:
pcd

         pca1      pca2      pca3      pca4    species
0    0.520559 -0.060927 -0.059730 -0.008994     setosa
1    0.701311  0.485876  0.122953  0.051163     setosa
2    0.552918  0.051798 -0.086993 -0.115110     setosa
3    0.516303 -0.136331  0.122057  0.016992     setosa
4    0.630474  0.131325 -0.087671 -0.012848     setosa
..        ...       ...       ...       ...        ...
122  0.096739 -0.070207  0.067647 -0.039236  virginica
123  0.133629 -0.335922 -0.219053  0.050464  virginica
124 -0.609117  0.387190  0.082811 -0.064624  virginica
125  0.046569 -0.179853  0.064061 -0.006483  virginica
126  0.624693  0.094399  0.051289 -0.024097  virginica

[127 rows x 5 columns]

In [67]:
fig = px.scatter_3d(pcd,
    x='pca1',y='pca2',z='pca3',
    color='species',
    title='pca_3D_plot',
    # color_continuous_scale='RdBu'
)
fig.show()

In [68]:
fig = px.line(
    x = range(1,len(pca.explained_variance_ratio_)+1),
    y = pca.explained_variance_ratio_.cumsum(),
    markers = True,
    labels = {'x': 'number of componets','y':'convergence'}
)
fig.add_hline(line_dash='dash',y=0.90,line_color='yellow',annotation_text='90% threshold')
fig.show()

In [69]:
model = DecisionTreeClassifier()

In [70]:
trined_model = model.fit(pca_train,y_train_encoded)

In [71]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [72]:
y_pred = model.predict(pca_test)

In [73]:
print(f'acurracy is {accuracy_score(y_test_encoded,y_pred)}')

acurracy is 0.2608695652173913

In [74]:
confusion_matrix(y_test_encoded,y_pred)

array([[0, 0, 8],
       [0, 0, 9],
       [0, 0, 6]])